package njlox;

enum TokenType {
	// SINGLE CHAR TOKEN
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

	// ONE TWO CHAR TOKEN
	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESSER, LESSER_EQUAL,

	// LITERALS
	IDENTIFIER, STRING, NUMBER,

	// KEYWORDS
	AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NULL, OR,
	PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

	EOF
}
